//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gss.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gss.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string AccessDeniedErrorString {
            get {
                return ResourceManager.GetString("AccessDeniedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload image to cloud..
        /// </summary>
        public static string AzureUploadFailedErrorString {
            get {
                return ResourceManager.GetString("AzureUploadFailedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input data..
        /// </summary>
        public static string BadRequestErrorString {
            get {
                return ResourceManager.GetString("BadRequestErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} creation failed..
        /// </summary>
        public static string CreationFailedErrorString {
            get {
                return ResourceManager.GetString("CreationFailedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deletion failed..
        /// </summary>
        public static string DeletionFailedErrorString {
            get {
                return ResourceManager.GetString("DeletionFailedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already confirmed..
        /// </summary>
        public static string EmailAlreadyConfirmedErrorString {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not confirmed..
        /// </summary>
        public static string EmailNotConfirmedErrorString {
            get {
                return ResourceManager.GetString("EmailNotConfirmedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add sensor to microcontroller..
        /// </summary>
        public static string FailedAddingSensorToMicrocontrollerErrorString {
            get {
                return ResourceManager.GetString("FailedAddingSensorToMicrocontrollerErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove sensor from microcontroller..
        /// </summary>
        public static string FailedRemovingSensorFromMicrocontrollerErrorString {
            get {
                return ResourceManager.GetString("FailedRemovingSensorFromMicrocontrollerErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send {0}..
        /// </summary>
        public static string FailedToSendEmailErrorString {
            get {
                return ResourceManager.GetString("FailedToSendEmailErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error (500)
        ///
        ///Ooops somthing went wrong on our end....
        /// </summary>
        public static string InternalServerErrorString {
            get {
                return ResourceManager.GetString("InternalServerErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email change token..
        /// </summary>
        public static string InvalidEmailChangeTokenErrorString {
            get {
                return ResourceManager.GetString("InvalidEmailChangeTokenErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email confirmation token..
        /// </summary>
        public static string InvalidEmailConfirmationTokenErrorString {
            get {
                return ResourceManager.GetString("InvalidEmailConfirmationTokenErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email..
        /// </summary>
        public static string InvalidEmailErrorString {
            get {
                return ResourceManager.GetString("InvalidEmailErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string InvalidEmailOrPasswordErrorString {
            get {
                return ResourceManager.GetString("InvalidEmailOrPasswordErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)..
        /// </summary>
        public static string InvalidGuidErrorString {
            get {
                return ResourceManager.GetString("InvalidGuidErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password reset token..
        /// </summary>
        public static string InvalidPasswordResetTokenErrorString {
            get {
                return ResourceManager.GetString("InvalidPasswordResetTokenErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings..
        /// </summary>
        public static string InvalidSettingsErrorString {
            get {
                return ResourceManager.GetString("InvalidSettingsErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri is invalid..
        /// </summary>
        public static string InvalidUriErrorString {
            get {
                return ResourceManager.GetString("InvalidUriErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension is missing..
        /// </summary>
        public static string MissingFileExtensionErrorString {
            get {
                return ResourceManager.GetString("MissingFileExtensionErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image extension is missing,.
        /// </summary>
        public static string MissingImageExtensionErrorString {
            get {
                return ResourceManager.GetString("MissingImageExtensionErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        public static string NotFoundErrorString {
            get {
                return ResourceManager.GetString("NotFoundErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token expired..
        /// </summary>
        public static string RefreshTokenExpiredErrorString {
            get {
                return ResourceManager.GetString("RefreshTokenExpiredErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token doesn&apos;t exist..
        /// </summary>
        public static string RefreshTokenNotExistsErrorString {
            get {
                return ResourceManager.GetString("RefreshTokenNotExistsErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized (401)
        ///
        ///Through a series of highly sophisticated and complex algorithms, this system has determined that you are not presently authorized to use this system function. It could be that you simply mistyped a password, or, it could be that you are some sort of interplanetary alien-being that has no hands and, thus, cannot type. If I were a gambler, I would bet that a cat (an orange tabby named Sierra or Harley) somehow jumped onto your keyboard and forgot some of the more important pointers from  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UnauthorizedMessageErrorString {
            get {
                return ResourceManager.GetString("UnauthorizedMessageErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported image extension. Supproted image extensions: {0}..
        /// </summary>
        public static string UnsupportedImageExtensionErrorString {
            get {
                return ResourceManager.GetString("UnsupportedImageExtensionErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} update failed..
        /// </summary>
        public static string UpdateFailedErrorString {
            get {
                return ResourceManager.GetString("UpdateFailedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out..
        /// </summary>
        public static string UserIsLockedOutErrorString {
            get {
                return ResourceManager.GetString("UserIsLockedOutErrorString", resourceCulture);
            }
        }
    }
}
