services:
  web:
    image: gss.web
    container_name: Gss.Web
    build:
      context: .
      dockerfile: Gss.Web/Dockerfile
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telemetry-dashboard:18889
    depends_on:
      identity-provider:
        condition: service_healthy
      db:
        condition: service_healthy
      db-migrations:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/_health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3

  db-migrations:
    image: gss.migrations
    container_name: Gss.Migrations
    build:
      context: .
      dockerfile: ./Dockerfile.migrator
    depends_on:
      db:
        condition: service_healthy

  microcontroller-listener:
    image: gss.microcontroller-listener
    container_name: Gss.MicrocontrollerListener
    build:
      context: .
      dockerfile: Gss.MicrocontrollerListener/Dockerfile
    ports:
      - 5002:5002/udp
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telemetry-dashboard:18889
    depends_on:
      db:
        condition: service_healthy
      message-broker:
        condition: service_healthy

  microcontroller-data-handler:
    image: gss.microcontroller-data-handler
    container_name: Gss.MicrocontrollerDataHandler
    build:
      context: .
      dockerfile: Gss.MicrocontrollerDataHandler/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telemetry-dashboard:18889
    depends_on:
      message-broker:
        condition: service_healthy
      db:
        condition: service_healthy
      identity-provider:
        condition: service_healthy
      email:
        condition: service_started

  identity-provider:
    image: quay.io/keycloak/keycloak:latest
    container_name: Gss.KeyCloak
    command: start-dev --import-realm
    ports:
      - 18080:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./.containers/keycloak:/opt/keycloak/data
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s

  db:
    image: postgres:latest
    container_name: Gss.PostgreSQL
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=GasSensorServer
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./.containers/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  message-broker:
    image: rabbitmq:4-management
    container_name: Gss.RabbitMQ
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  email:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: Gss.PapercutSMTP
    ports:
      - 5500:80
      - 25:25

  telemetry-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: Gss.AspireDashboard
    ports:
      - 18888:18888
      - 18889:18889
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true