// <auto-generated />
using System;
using Gss.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gss.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241118151251_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gss.Core.Entities.Microcontroller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastResponseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RequestedMicrocontrollerSensorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Microcontrollers");
                });

            modelBuilder.Entity("Gss.Core.Entities.MicrocontrollerSensors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CriticalValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("MicrocontrollerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MicrocontrollerId");

                    b.HasIndex("SensorId");

                    b.ToTable("MicrocontrollerSensors");
                });

            modelBuilder.Entity("Gss.Core.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("Gss.Core.Entities.SensorData", b =>
                {
                    b.Property<Guid>("MicrocontrollerSensorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("MicrocontrollerSensorId", "ReadTime");

                    b.ToTable("SensorsData");
                });

            modelBuilder.Entity("Gss.Core.Entities.SensorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Units")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("SensorsTypes");
                });

            modelBuilder.Entity("Gss.Core.Entities.MicrocontrollerSensors", b =>
                {
                    b.HasOne("Gss.Core.Entities.Microcontroller", "Microcontroller")
                        .WithMany("MicrocontrollerSensors")
                        .HasForeignKey("MicrocontrollerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gss.Core.Entities.Sensor", "Sensor")
                        .WithMany("SensorMicrocontrollers")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Microcontroller");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Gss.Core.Entities.Sensor", b =>
                {
                    b.HasOne("Gss.Core.Entities.SensorType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Gss.Core.Entities.SensorData", b =>
                {
                    b.HasOne("Gss.Core.Entities.MicrocontrollerSensors", null)
                        .WithMany()
                        .HasForeignKey("MicrocontrollerSensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gss.Core.Entities.Microcontroller", b =>
                {
                    b.Navigation("MicrocontrollerSensors");
                });

            modelBuilder.Entity("Gss.Core.Entities.Sensor", b =>
                {
                    b.Navigation("SensorMicrocontrollers");
                });
#pragma warning restore 612, 618
        }
    }
}
