// <auto-generated />
using System;
using Gss.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gss.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241116232250_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gss.Core.Entities.Microcontroller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastResponseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RequestedSensorID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Microcontrollers");
                });

            modelBuilder.Entity("Gss.Core.Entities.MicrocontrollerSensors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CriticalValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("MicrocontrollerID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SensorID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MicrocontrollerID");

                    b.HasIndex("SensorID");

                    b.ToTable("MicrocontrollerSensors");
                });

            modelBuilder.Entity("Gss.Core.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TypeID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeID");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("Gss.Core.Entities.SensorData", b =>
                {
                    b.Property<Guid>("MicrocontrollerID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SensorID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ValueReadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SensorValue")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ValueReceivedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MicrocontrollerID", "SensorID", "ValueReadTime");

                    b.HasIndex("SensorID");

                    b.ToTable("SensorsData");
                });

            modelBuilder.Entity("Gss.Core.Entities.SensorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Units")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("SensorsTypes");
                });

            modelBuilder.Entity("Gss.Core.Entities.MicrocontrollerSensors", b =>
                {
                    b.HasOne("Gss.Core.Entities.Microcontroller", "Microcontroller")
                        .WithMany("MicrocontrollerSensors")
                        .HasForeignKey("MicrocontrollerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gss.Core.Entities.Sensor", "Sensor")
                        .WithMany("SensorMicrocontrollers")
                        .HasForeignKey("SensorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Microcontroller");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Gss.Core.Entities.Sensor", b =>
                {
                    b.HasOne("Gss.Core.Entities.SensorType", "Type")
                        .WithMany("Sensors")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Gss.Core.Entities.SensorData", b =>
                {
                    b.HasOne("Gss.Core.Entities.Microcontroller", "Microcontroller")
                        .WithMany()
                        .HasForeignKey("MicrocontrollerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gss.Core.Entities.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Microcontroller");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Gss.Core.Entities.Microcontroller", b =>
                {
                    b.Navigation("MicrocontrollerSensors");
                });

            modelBuilder.Entity("Gss.Core.Entities.Sensor", b =>
                {
                    b.Navigation("SensorMicrocontrollers");
                });

            modelBuilder.Entity("Gss.Core.Entities.SensorType", b =>
                {
                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
